[project]
name = "mypackage"
description = "A simple template for a python package."
authors = [
    {name = "Jacob Crabtree", email = "crabtr26@gmail.com"}
]
license = {file = "LICENSE"}
readme = {file = "README.md", content-type = "text/markdown"}
# version = "1.0.0"
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.6"
dependencies = [
    "pandas>=1.4",
]

dynamic = ["version"]

[project.urls]
repository = "https://github.com/crabtr26/python-templates"

[build-system]
requires = ["setuptools", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = [
    "pylint>=2.13",
    "flake8>=3.9",
    "isort>=5.10",
    "pre-commit>=2.19",
    "black>=22.3",
    "pytest>=7.1",
    "pytest-asyncio>=0.18",
    "pytest-cov>=3.0",
    "sphinx>=4.5",
    "sphinx-rtd-theme>=1.0",
]

[project.scripts]
greet = "app:main"
