name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python package
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install virtualenv
      run: pip install virtualenv
    - name: Create venv
      run: virtualenv venv
    - name: Install package
      run: source venv/bin/activate && pip install .[dev]
    - name: Run tests and collect coverage
      run: source venv/bin/activate && pytest
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
