name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python package
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install package
      run: poetry install
    - name: Run tests and collect coverage
      run: poetry run pytest
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
